title: Olli.Schmitz | Blog
name: Oliver Schmitz
email: mail@ollischmitz.net
timezone: Europe/Berlin
description: >-
  My thoughts about Coding, Software Design, Architecture and other things
baseurl: "/"
url: "http://blog.ollischmitz.net"
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - postcss.config.js
  - webpack.config.js
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-paginate-v2
  - liquid_reading_time
  - liquid_pluralize
jekyll_compose:
  default_front_matter:
    drafts:
      layout: article      
      author:
      tags: []
      abstract:
    posts:  
      layout: article
      author:
      tags: []
      abstract:
      image:
      image-alt:
      image-credits:
pagination:
  enabled: true   
  debug: true
  per_page: 3  
  permalink: '/page/:num'
  sort_field: 'date'
  sort_reverse: true